### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by T4bletopG4mes** [amoAR/AWA-Key-Checker#5]
Is dark mode a lie? I see it in the screenshots but there is not setting I can see in the code.

**Comment by amoAR** [comment]
The script doesn't include a dedicated dark mode setting because it is designed to work harmoniously with the browser's forced dark mode feature. The colors, such as background-color, were carefully selected to ensure they look good in both normal and inverted color schemes. This way, the script automatically adapts to the user's preferred color scheme without needing a separate toggle for dark mode.

**Comment by T4bletopG4mes** [comment]
AWA doesnt have dark mode for the giveaways page though, thats a 3rd party thing most likely lol

**Comment by amoAR** [comment]
AFAIK it doesn't have dark mode at all. Like I said it depends on the browser schema, nothing else.
